/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IComplianceService__factory } from "./IComplianceService__factory";
export { IRegistryService__factory } from "./IRegistryService__factory";
export { ITrustService__factory } from "./ITrustService__factory";
