/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITrustService,
  ITrustServiceInterface,
} from "../../../contracts/interfaces/ITrustService";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "addr",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "oldRole",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newRole",
        type: "uint256",
      },
    ],
    name: "RoleChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "roleOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "role",
        type: "uint256",
      },
    ],
    name: "setRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITrustService__factory {
  static readonly abi = _abi;
  static createInterface(): ITrustServiceInterface {
    return new Interface(_abi) as ITrustServiceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITrustService {
    return new Contract(address, _abi, runner) as unknown as ITrustService;
  }
}
