version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: xrwa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - xrwa-network

  # Redis (for caching)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - xrwa-network

  # Backend API
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=xrwa
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - BLOCKCHAIN_RPC_URL=http://hardhat:8545
      - BLOCKCHAIN_PRIVATE_KEY=your-private-key
      - TRUST_SERVICE_ADDRESS=0x...
      - REGISTRY_SERVICE_ADDRESS=0x...
      - COMPLIANCE_SERVICE_ADDRESS=0x...
      - DS_TOKEN_ADDRESS=0x...
    depends_on:
      - postgres
      - redis
    networks:
      - xrwa-network

  # Frontend
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - xrwa-network

  # Hardhat Local Network
  hardhat:
    build:
      context: ./contract
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    networks:
      - xrwa-network

volumes:
  postgres_data:

networks:
  xrwa-network:
    driver: bridge