/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ComplianceServiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "blacklistedAddresses"
      | "complianceMode"
      | "cooldownPeriod"
      | "countryCompliance"
      | "dailyTransactionLimit"
      | "dailyTransactionVolume"
      | "getCooldownStatus"
      | "getDailyTransactionVolume"
      | "lastTransactionTime"
      | "maxHolders"
      | "maxTransactionAmount"
      | "owner"
      | "preIssuanceCheck"
      | "preTransferCheck"
      | "registry"
      | "renounceOwnership"
      | "setBlacklistedAddress"
      | "setComplianceMode"
      | "setCooldownPeriod"
      | "setCountryCompliance"
      | "setMaxHolders"
      | "setTransactionLimits"
      | "transferOwnership"
      | "trust"
      | "updateServices"
      | "validateBurn"
      | "validateIssuance"
      | "validateSeize"
      | "validateTransfer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplianceViolation"
      | "OwnershipTransferred"
      | "PolicyChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "blacklistedAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "complianceMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cooldownPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "countryCompliance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyTransactionLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyTransactionVolume",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCooldownStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyTransactionVolume",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastTransactionTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxHolders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTransactionAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "preIssuanceCheck",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "preTransferCheck",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBlacklistedAddress",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setComplianceMode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCooldownPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCountryCompliance",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxHolders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransactionLimits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "trust", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateServices",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateBurn",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateIssuance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateSeize",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "blacklistedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "complianceMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cooldownPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "countryCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyTransactionLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyTransactionVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCooldownStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyTransactionVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastTransactionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxHolders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxTransactionAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "preIssuanceCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "preTransferCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBlacklistedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setComplianceMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCooldownPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCountryCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxHolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransactionLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trust", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateIssuance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateSeize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTransfer",
    data: BytesLike
  ): Result;
}

export namespace ComplianceViolationEvent {
  export type InputTuple = [
    reason: string,
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [
    reason: string,
    from: string,
    to: string,
    value: bigint
  ];
  export interface OutputObject {
    reason: string;
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyChangedEvent {
  export type InputTuple = [policy: string, data: BytesLike];
  export type OutputTuple = [policy: string, data: string];
  export interface OutputObject {
    policy: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceService extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceService;
  waitForDeployment(): Promise<this>;

  interface: ComplianceServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  blacklistedAddresses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  complianceMode: TypedContractMethod<[], [bigint], "view">;

  cooldownPeriod: TypedContractMethod<[], [bigint], "view">;

  countryCompliance: TypedContractMethod<[arg0: string], [boolean], "view">;

  dailyTransactionLimit: TypedContractMethod<[], [bigint], "view">;

  dailyTransactionVolume: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getCooldownStatus: TypedContractMethod<
    [addr: AddressLike],
    [[boolean, bigint] & { canTransact: boolean; remainingTime: bigint }],
    "view"
  >;

  getDailyTransactionVolume: TypedContractMethod<
    [addr: AddressLike, date: BigNumberish],
    [bigint],
    "view"
  >;

  lastTransactionTime: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  maxHolders: TypedContractMethod<[], [bigint], "view">;

  maxTransactionAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  preIssuanceCheck: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "view"
  >;

  preTransferCheck: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBlacklistedAddress: TypedContractMethod<
    [addr: AddressLike, blacklisted: boolean],
    [void],
    "nonpayable"
  >;

  setComplianceMode: TypedContractMethod<
    [mode: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCooldownPeriod: TypedContractMethod<
    [_cooldownPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCountryCompliance: TypedContractMethod<
    [country: string, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setMaxHolders: TypedContractMethod<
    [_maxHolders: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTransactionLimits: TypedContractMethod<
    [_maxTransactionAmount: BigNumberish, _dailyTransactionLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trust: TypedContractMethod<[], [string], "view">;

  updateServices: TypedContractMethod<
    [_registry: AddressLike, _trust: AddressLike],
    [void],
    "nonpayable"
  >;

  validateBurn: TypedContractMethod<
    [who: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "nonpayable"
  >;

  validateIssuance: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "nonpayable"
  >;

  validateSeize: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "nonpayable"
  >;

  validateTransfer: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "blacklistedAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "complianceMode"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cooldownPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "countryCompliance"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "dailyTransactionLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyTransactionVolume"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCooldownStatus"
  ): TypedContractMethod<
    [addr: AddressLike],
    [[boolean, bigint] & { canTransact: boolean; remainingTime: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDailyTransactionVolume"
  ): TypedContractMethod<
    [addr: AddressLike, date: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastTransactionTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxHolders"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxTransactionAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "preIssuanceCheck"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "preTransferCheck"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBlacklistedAddress"
  ): TypedContractMethod<
    [addr: AddressLike, blacklisted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setComplianceMode"
  ): TypedContractMethod<[mode: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCooldownPeriod"
  ): TypedContractMethod<[_cooldownPeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCountryCompliance"
  ): TypedContractMethod<
    [country: string, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxHolders"
  ): TypedContractMethod<[_maxHolders: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTransactionLimits"
  ): TypedContractMethod<
    [_maxTransactionAmount: BigNumberish, _dailyTransactionLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trust"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateServices"
  ): TypedContractMethod<
    [_registry: AddressLike, _trust: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateBurn"
  ): TypedContractMethod<
    [who: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateIssuance"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateSeize"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateTransfer"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "nonpayable"
  >;

  getEvent(
    key: "ComplianceViolation"
  ): TypedContractEvent<
    ComplianceViolationEvent.InputTuple,
    ComplianceViolationEvent.OutputTuple,
    ComplianceViolationEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyChanged"
  ): TypedContractEvent<
    PolicyChangedEvent.InputTuple,
    PolicyChangedEvent.OutputTuple,
    PolicyChangedEvent.OutputObject
  >;

  filters: {
    "ComplianceViolation(string,address,address,uint256)": TypedContractEvent<
      ComplianceViolationEvent.InputTuple,
      ComplianceViolationEvent.OutputTuple,
      ComplianceViolationEvent.OutputObject
    >;
    ComplianceViolation: TypedContractEvent<
      ComplianceViolationEvent.InputTuple,
      ComplianceViolationEvent.OutputTuple,
      ComplianceViolationEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PolicyChanged(string,bytes)": TypedContractEvent<
      PolicyChangedEvent.InputTuple,
      PolicyChangedEvent.OutputTuple,
      PolicyChangedEvent.OutputObject
    >;
    PolicyChanged: TypedContractEvent<
      PolicyChangedEvent.InputTuple,
      PolicyChangedEvent.OutputTuple,
      PolicyChangedEvent.OutputObject
    >;
  };
}
