/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ComplianceService } from "./ComplianceService";
export type { DSToken } from "./DSToken";
export type { RegistryService } from "./RegistryService";
export type { StableCoin } from "./StableCoin";
export type { StableCoinFactory } from "./StableCoinFactory";
export type { TrustService } from "./TrustService";
