/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IComplianceService } from "./IComplianceService";
export type { IRegistryService } from "./IRegistryService";
export type { ITrustService } from "./ITrustService";
