/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ITrustServiceInterface extends Interface {
  getFunction(nameOrSignature: "roleOf" | "setRole"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RoleChanged"): EventFragment;

  encodeFunctionData(functionFragment: "roleOf", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setRole",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "roleOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRole", data: BytesLike): Result;
}

export namespace RoleChangedEvent {
  export type InputTuple = [
    addr: AddressLike,
    oldRole: BigNumberish,
    newRole: BigNumberish
  ];
  export type OutputTuple = [addr: string, oldRole: bigint, newRole: bigint];
  export interface OutputObject {
    addr: string;
    oldRole: bigint;
    newRole: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ITrustService extends BaseContract {
  connect(runner?: ContractRunner | null): ITrustService;
  waitForDeployment(): Promise<this>;

  interface: ITrustServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  roleOf: TypedContractMethod<[addr: AddressLike], [bigint], "view">;

  setRole: TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "roleOf"
  ): TypedContractMethod<[addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setRole"
  ): TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "RoleChanged"
  ): TypedContractEvent<
    RoleChangedEvent.InputTuple,
    RoleChangedEvent.OutputTuple,
    RoleChangedEvent.OutputObject
  >;

  filters: {
    "RoleChanged(address,uint256,uint256)": TypedContractEvent<
      RoleChangedEvent.InputTuple,
      RoleChangedEvent.OutputTuple,
      RoleChangedEvent.OutputObject
    >;
    RoleChanged: TypedContractEvent<
      RoleChangedEvent.InputTuple,
      RoleChangedEvent.OutputTuple,
      RoleChangedEvent.OutputObject
    >;
  };
}
